#!/bin/bash
#
# A visual diffs for the images in the git repository.

diff() {
	compare "$2" "$1" png:- \
		| montage -resize 445x -label %f -frame 5 -geometry +0+0 "$2" - "$1" png:- \
		| display -title "$1" -
}

diff "$@"
